### PR TITLE
helm 3.6.2, kubectl 1.21.2

### PR DESCRIPTION
**Pull request by dtzar**

### CODE REVIEW

**Comment by gaby** [comment]
I was working on adding these changes yesterday. Also to add the versions back into the Dockerfile, to avoid the failures in hub.docker.com

**Comment by dtzar** [comment]
Ok - I didn't see your branch up here so I didn't know... You want merge this then PR the fixes to docker build?

**Comment by gaby** [comment]
Seems like the Docker stage is now showing up here? So it wont let me merge it

**Comment by gaby** [comment]
For some reason the docker stage is now showing here, and it won't let me merge cause of that.

I will take a look during the weekend, my branch is in a fork.

**Pull request merged**
