### PR TITLE
GCloud support

### PR DESCRIPTION
**Pull request by Svisstack**
You can't deploy using helm or kubectl without the gcloud for authentication, so the tools are unusable without the gcloud inside of for deploy to GKE it which have first-class kubernetes support.

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
@Svisstack The main purpose of this docker image is to be a lightweight image to be use during CI deployments. 

Your changes are increasing the size of the final image from 113MB to 875MB.

**Comment by Svisstack** [comment]
Thats a lot for sure. We created the PR as we does not understand benefits of having the lightweight image in Ci/Cd, it's make sense for running software but not for executing just few kubectl or helm commands. Way better approach is to have image that can be used to deploy charts or use kubectl across all cloud and on perm platforms without using multiple images. I understand that this could be not merged and we will just maintain this logic on our fork.

**Comment by gabrielcalderon** [comment]
At least in my case, just having a kubeconfig/credentials to my Docker Registry is enough to deploy applications from Gitlab-CI, etc. I noticed that Google already has an image for gcloud ([here](https://github.com/GoogleCloudPlatform/cloud-sdk-docker)), but it's missing Helm.

**Comment by dtzar** [comment]
Agree with @gabrielcalderon the goal of this image is to keep it lightweight.

**Pull request closed without merging**
