### PR TITLE
Support for Helm 3.4.0 and k8s 1.19.3

### PR DESCRIPTION
**Pull request by gabrielcalderon**
* Added support for Helm 3.4.0 that was released today.

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
Release notes: [https://github.com/helm/helm/releases/tag/v3.4.0](https://github.com/helm/helm/releases/tag/v3.4.0)

**Comment by gabrielcalderon** [comment]
@dtzar Another one 😄

**Review by dtzar — APPROVED** [review]

**Comment by dunn** [comment]
should there be a tag for this release?

**Comment by gabrielcalderon** [comment]
@dunn Correct it is missing. The CI still published the image with tag 3.4.0 to Docker Hub.

https://hub.docker.com/layers/dtzar/helm-kubectl/3.4.0/images/sha256-c94bfb5d346584d8c158e63bf68054c186fde437201804584c59bf99ef5872f4?context=explore

**Pull request merged**
