### PR TITLE
added support for helm 2.17.0

### PR DESCRIPTION
**Pull request by massimilianobraglia**
hey @dtzar, thank you for this one :)

https://helm.sh/blog/new-location-stable-incubator-charts/
As of new stable repo location, it is recommended to update to helm 2.17.0

### CODE REVIEW

**Comment by varnem2** [comment]
Bump

@dtzar anything we can do to helm move this PR along?

**Comment by gabrielcalderon** [comment]
@massimilianobraglia Fix your merge conflicts. You removed almost half the README file in your PR.

**Comment by massimilianobraglia** [comment]
@gabrielcalderon I did not, I targeted 2.16 tag as base of this PR. It is not written how to handle version upgrade prior to v3

**Comment by gabrielcalderon** [comment]
@massimilianobraglia I will take a look when i get out of work.

**Comment by massimilianobraglia** [comment]
Thank you, @gabrielcalderon!

**Review by gabrielcalderon — APPROVED** [review]
👍🏻 Looks good now!

**Review by gabrielcalderon — APPROVED** [review]
👍🏻

**Comment by gabrielcalderon** [comment]
@massimilianobraglia Image is now available 

```
docker pull dtzar/helm-kubectl:2.17.0
```

**Comment by massimilianobraglia** [comment]
Thank you very much, @gabrielcalderon!

**Pull request merged**
