### PR TITLE
Helm 3.3.4, and Kubectl 1.19.2 Support

### PR DESCRIPTION
**Pull request by gabrielcalderon**
* Update to latest version of Helm, Kubectl.
* Updated Alpine to 3.12

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
I also notice that several versions of Kubectl and Helm are missing. Any plans to add those, or do those just get skipped?

**Comment by gabrielcalderon** [comment]
Even thou the Readme states Alpine 3.12 is being used, the Dockerfile says otherwise. I updated that too.

**Comment by framled** [comment]
It's gonna be awesome create an image for 3.3.4 with kube 17, 18 y 19

**Comment by gabrielcalderon** [comment]
@dtzar Are you still active on this repo?

**Review by dtzar — APPROVED** [review]

**Comment by dtzar** [comment]
I've had a lot of life things going on, so sorry for the delay. That said I'd welcome others who would like to maintain this repo with me

**Comment by gabrielcalderon** [comment]
@dtzar No worries, I understand. I can help maintain the repo. This image is critical for my CI pipelines 😁

**Comment by framled** [comment]
@dtzar me too 👍

**Pull request merged**
