### PR TITLE
Add openssh

### PR DESCRIPTION
**Pull request by karlAlnebratt**
- To have git working on `CircleCi` we need to add `openssh`

### CODE REVIEW

**Comment by karlAlnebratt** [comment]
@dtzar Thanks for a nice and clean docker image with`helm` and `kubectl`
We are using it on `circleCI` and have issues with git not working. It would be nice to add `openssh` to this image

**Comment by karlAlnebratt** [comment]
Cool thanks

**Comment by karlAlnebratt** [comment]
Will, this be patched released? Or will you wait for the next helm to release?

**Comment by dtzar** [comment]
The docker hub image was automatically patched/released after I merged your PR ;)

**Comment by karlAlnebratt** [comment]
Nice. Thanks!

**Pull request merged**
